# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]
jobs:
  test-coverage:
    name: Test on Node.js Latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js latest
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "15"
      - name: Install dependencies
        run: npm install
      - name: Generate coverage report
        run: npm run test-coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.4.0
        with:
          token: ${{ secrets.CODECOV }}
  test-node-12:
    name: Test on Node.js v12
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codd
        uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "12"
          
